/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-08-31 12:39:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626931046785L));
    _jspx_dependants.put("jar:file:/C:/Users/ASUS/Documents/mshyunsik/JAVA/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/TravelShare/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.highcharts.com/maps/highmaps.js\"></script>\r\n");
      out.write("<script src=\"http://code.highcharts.com/maps/modules/drilldown.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/main_chart.js?ver=5.21\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var highMap = new highMaps();\r\n");
      out.write("highMap.init();\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/main.css?ver=5.17\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/main_board.css?ver=1.00\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Two+Tone|Material+Icons+Sharp|Material+Icons+Outlined\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"#\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <main>\r\n");
      out.write("        <!-- 메인섹션 -->\r\n");
      out.write("        <section id=\"main_sec1\">\r\n");
      out.write("            <div class=\"main_backgroundImg\"></div>\r\n");
      out.write("            <div class=\"main_container\">\r\n");
      out.write("				");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header/top.jsp", out, false);
      out.write("\r\n");
      out.write("                <div class=\"main_mainBar\">\r\n");
      out.write("                    <div id=\"main_content\">\r\n");
      out.write("                        <div class=\"main_travel\">\r\n");
      out.write("                            Travel<span style=\"color: orangered;\">ers</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"main_writing\">\r\n");
      out.write("                            <div>여행 일자, 숙소, 가고 싶은 장소만\r\n");
      out.write("                                선택하면 일정이 자동으로 완성되는\r\n");
      out.write("                                쉽고 간편한 여행 일정 플래너</div>\r\n");
      out.write("                            <div class=\"main_start\">START</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- <div id=\"main_map\"></div> -->\r\n");
      out.write("                    <div></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <footer></footer>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 여행섹션 -->\r\n");
      out.write("        <section>    \r\n");
      out.write("            <div class=\"main_sec2_topbar1\">여행 루트</div>\r\n");
      out.write("            <div class=\"main_sec2_topbar2\">여행지를 직접 검색하시거나 목록에서 선택해주세요.</div>\r\n");
      out.write("            <div class=\"main_sec2_topbar3\">\r\n");
      out.write("                <input class=\"main_textInput\" type=\"text\" placeholder=\"어디로 여행을 떠나시나요?\">\r\n");
      out.write("                <span class=\"material-icons-outlined\" id=\"main_textSearch\" style=\"font-size: calc(20px + 1vw);\">search</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"main_map_container\">\r\n");
      out.write("                <div id=\"main_map\" class=\"main_map_app\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- 추천섹션 -->\r\n");
      out.write("        <section id=\"main_sec3\">\r\n");
      out.write("            <div id=\"main_sev3_container1\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span id=\"main_sev3_text_1\">우리나라에 이런 곳이 있었어???</span><br>\r\n");
      out.write("                    <span id=\"main_sev3_text_2\">Best Travel<span style=\"color: orangered;\">ers</span> Course!</span>\r\n");
      out.write("                    <div class=\"main_recommend\">\r\n");
      out.write("                        <div class=\"board_content\" id=\"board_content\">\r\n");
      out.write("                            <div class=\"board_imgContent\">\r\n");
      out.write("                                <img alt=\"\"\r\n");
      out.write("                                    src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/back1.jpg\">\r\n");
      out.write("                                <img alt=\"\"\r\n");
      out.write("                                    src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/back2.jpg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"board_textContent\">\r\n");
      out.write("                                <div class=\"board_text1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                <div class=\"board_textTit\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"board_option\">\r\n");
      out.write("                                <div class=\"board_areaPan\">\r\n");
      out.write("                                    <span class=\"material-icons-outlined board_area_img\">\r\n");
      out.write("                                        location_on </span>\r\n");
      out.write("                                    <div class=\"board_area\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.area }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"board_likePan\">\r\n");
      out.write("                                    <span class=\"material-icons-outlined board_like_img\">\r\n");
      out.write("                                        favorite </span>\r\n");
      out.write("                                    <div class=\"like\">0명</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"hrClass\">\r\n");
      out.write("            <div id=\"main_sev3_container2\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span id=\"main_sev3_text_1\">머선129? 한번 가보긴 했나~?</span><br>\r\n");
      out.write("                    <span id=\"main_sev3_text_2\">Travel<span style=\"color: orangered;\">ers</span>가 추천해드려요~!</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 스크롤섹션 -->\r\n");
      out.write("\r\n");
      out.write("        <section>\r\n");
      out.write("            <section class=\"scroll-content\">\r\n");
      out.write("                <div class=\"scroll-graphic\">\r\n");
      out.write("                    <div class=\"main_sticky_container1\">\r\n");
      out.write("                        <div class=\"main_sticky_text\">\r\n");
      out.write("                            <p>#사랑하는 연인 #커플 #부부</p>\r\n");
      out.write("                            <p>소중하고 사랑스러운 하루를 Travel<span style=\"color: orangered;\">ers</span>에서 함께</p>\r\n");
      out.write("                            <p>당신의 행복했던 하루를 다른 Traveler와 공유해보세요</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"main_sticky_text\">\r\n");
      out.write("                            <p>#하나뿐인 가족 #형제 #자매 #부모님</p>\r\n");
      out.write("                            <p>가족들과 잊지 못할 추억여행을 Travel<span style=\"color: orangered;\">ers</span>에서 함께</p>\r\n");
      out.write("                            <p>당신의 행복했던 하루를 다른 Traveler와 공유해보세요</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"main_sticky_text\">\r\n");
      out.write("                            <p>#불알친구 #동아리 #모임</p>\r\n");
      out.write("                            <p>익사이팅하고 신나는 여행을 Travel<span style=\"color: orangered;\">ers</span>에서 함께</p>\r\n");
      out.write("                            <p>당신의 행복했던 하루를 다른 Traveler와 공유해보세요</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"main_sticky_container2\">\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/mainlogo.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- <div class=\"graphic-item\"><img class=\"scene-img\" src=\"./asset/배경1.jpg\" alt=\"\"></div> -->\r\n");
      out.write("                    <div class=\"main_cellphone\">\r\n");
      out.write("                        <div class=\"main_cellphone_list\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/back1.jpg\" alt=\"\"></div>\r\n");
      out.write("                        <div class=\"main_cellphone_list\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/back2.jpg\" alt=\"\"></div>\r\n");
      out.write("                        <div class=\"main_cellphone_list\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/back3.jpg\" alt=\"\"></div>\r\n");
      out.write("                        <div><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/cellphone.png\" alt=\"\" id=\"main_cellphoneImg\"></div>\r\n");
      out.write("                    </div>   \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"scroll-text global-width\">\r\n");
      out.write("                    <div class=\"main_scroll_height\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <section class=\"main_lastWord global-width\">\r\n");
      out.write("            	<div>\r\n");
      out.write("	                <h2>일상을 떠나는 사람들</h2>\r\n");
      out.write("	                <p>업무에 시달리고, 학업에 시달리는 여러분들을 위해 하루의 행복한 시간을 선물해드립니다.<br></p>\r\n");
      out.write("            	</div>\r\n");
      out.write("            	<div>\r\n");
      out.write("	                <h2>St. Auhustine</h2>\r\n");
      out.write("    	            <p>여행하지 않는 사람들에게는, 이 세상이 한 페이지만 읽은 책과 같다.</p>\r\n");
      out.write("            	</div>\r\n");
      out.write("                <div>\r\n");
      out.write("	                <h2>Lin Yutang</h2>\r\n");
      out.write("	                <p>여행이 얼마나 아름다운 것인지는, 집으로 돌아와 오래되고 친숙한 베개에 누워 쉴 때까지 깨닫지 못한다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("	                <h2>고도원 ‘사랑합니다, 감사합니다’ 중</h2>\r\n");
      out.write("	                <p>인생은 여행이다. 여행은 떠나는 일이다. 오늘의 나를 떠나 어제의 나와 내일의 나를 만나는 일이다.힘들여 오늘을 살아가는\r\n");
      out.write("	                    나로부터 벗어나 새로운 나와 소통하는 일은 살아가면서 얼마나 중요한가. 타지에서의 깊은밤 낯선 침대에 누워 어둠에 안겨있노라면\r\n");
      out.write("	                    내가 있던 자리에 두고 온 많은 일들이 그 동안 내 삶을 얼마나 꽁꽁 묶어놓고 있었는지를 깨닫게 된다. 사람에 치이고 생활에 찌든\r\n");
      out.write("	                    현실의 무게는 늘 버거웠고 사랑에 배고픈 일상은 언제나 외로웠다. 오늘..아무리 삶이 버겁고 외로울지라도 언제나 사랑합니다.\r\n");
      out.write("	                    감사합니다... 한마디 하면서 살아가는 사람에게 행복은 늘 품 안에 있다. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!--             <footer class=\"footer_container\"> -->\r\n");
      out.write("<!--                <div> -->\r\n");
      out.write("<!--                     <div class=\"footer_logo\"></div> -->\r\n");
      out.write("<!--                     <div>Travel<span style=\"color: orangered;\">ers</span></div> -->\r\n");
      out.write("<!--                </div> -->\r\n");
      out.write("<!--                <div> -->\r\n");
      out.write("<!--                    <div onclick=\"location.href='#'\"></div> -->\r\n");
      out.write("<!--                    <div onclick=\"location.href='#'\"></div> -->\r\n");
      out.write("<!--                    <div onclick=\"location.href='#'\"></div> -->\r\n");
      out.write("<!--                    <div onclick=\"location.href='#'\"></div> -->\r\n");
      out.write("<!--                </div> -->\r\n");
      out.write("<!--                <div>A website created by the collaboration of the left team</div> -->\r\n");
      out.write("<!--             </footer> -->\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    <!-- popup창 -->\r\n");
      out.write("   	<div id=\"board_clickPan\" class=\"board_hide\">\r\n");
      out.write("		<div onclick=\"imgClickRollback()\" class=\"x_box\">\r\n");
      out.write("			<span class=\"material-icons-outlined \"> close </span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"board_detailContent\">\r\n");
      out.write("			<div class=\"board_detailPan\">\r\n");
      out.write("				<div class=\"board_left_pan\">\r\n");
      out.write("					<iframe id=\"board_googleMap\"\r\n");
      out.write("						src=\"https://www.google.com/maps?q= 서울 관악구 관악로 85 &output=embed\"\r\n");
      out.write("						style='border: 0;' allowfullscreen=\"\" aria-hidden=\"false\"\r\n");
      out.write("						tabindex=\"0\" frameborder=\"0\"></iframe>\r\n");
      out.write("					<!-- q= 뒤에 주소를 입력하면 됨 -->\r\n");
      out.write("					<hr style=\"color: black; width: 100%; margin-bottom: 50px;\">\r\n");
      out.write("					<div id=\"board_main_content\" class=\"board_main_content\">\r\n");
      out.write("						<!-- 게시판 콘텐츠들이 들어가는 곳  -->\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"board_comment\">\r\n");
      out.write("						<div id=\"board_comment_tit\" class=\"board_comment_tit\">\r\n");
      out.write("							<p>한줄댓글</p>\r\n");
      out.write("<!-- 									<div class=\"board_ud\"> -->\r\n");
      out.write("<!-- 										<button>수정</button> -->\r\n");
      out.write("<!-- 										<button>삭제</button> -->\r\n");
      out.write("<!-- 									</div> -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"board_comment_write\">\r\n");
      out.write("							<form action=\"#\" id=\"board_commentId\">\r\n");
      out.write("								<input type=\"text\" id=\"board_commnet\" name=\"board_commnet\"\r\n");
      out.write("									placeholder=\"한 줄 댓글을 남겨주세요.\" autocomplete=\"off\"> <input type=\"hidden\"\r\n");
      out.write("									id=\"user_id\" name=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input\r\n");
      out.write("									type=\"submit\" name=\"board_commnet_submit\" value=\"댓글남기기\">\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"board_comment_show\" class=\"board_comment_show\">\r\n");
      out.write("							<!-- 							<div class=\"board_comment_see\"> -->\r\n");
      out.write("							<!-- 								<div class=\"board_comment_see_img\"> -->\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("							<!-- 								</div> -->\r\n");
      out.write("							<!-- 								<div class=\"board_comment_see_text\"> -->\r\n");
      out.write("							<!-- 									<div> -->\r\n");
      out.write("							<!-- 										<strong>닉네임</strong> <span class=\"board_comment_see_text_date\">2021.08.12</span> -->\r\n");
      out.write("							<!-- 									</div> -->\r\n");
      out.write("							<!-- 									<div>내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용</div> -->\r\n");
      out.write("							<!-- 								</div> -->\r\n");
      out.write("							<!-- 							</div> -->\r\n");
      out.write("							<!-- 							<hr style=\"color: black; width: 100%; margin-bottom: 50px;\"> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"board_right_pan\">\r\n");
      out.write("					<div id=\"board_user_info\" class=\"board_user_info\">\r\n");
      out.write("						<img id=\"board_mainimg\"\r\n");
      out.write("							src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/null.jpg\"\r\n");
      out.write("							alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"board_user_name\" class=\"board_user_name\">닉네임</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"board_content_id\" class=\"board_content_id\"></div>\r\n");
      out.write("					<div id=\"board_title\" class=\"board_title\"></div>\r\n");
      out.write("					<div class=\"board_sub_info\">\r\n");
      out.write("						<div class=\"board_sub_info2\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<span class=\"material-icons-outlined board_area_img\">\r\n");
      out.write("									location_on </span>\r\n");
      out.write("								<div>추천 여행지</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"board_bestplace\">몰라</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"board_sub_info2\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<span class=\"material-icons-outlined\"> local_dining</span>\r\n");
      out.write("								<div>추천 맛집</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"board_besteat\">몰라</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"board_sub_info2\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<span class=\"material-icons-outlined board_like_img\">\r\n");
      out.write("									favorite </span>\r\n");
      out.write("								<div>스크랩</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"board_scarp_cnt\">0</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div>\r\n");
      out.write("						<div id=\"board_scrap_btn\" class=\"board_scrap_btn\">\r\n");
      out.write("							<span class=\"material-icons-outlined board_like_img\">\r\n");
      out.write("								favorite </span>\r\n");
      out.write("							<div>스크랩</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"board_travelPlans\">\r\n");
      out.write("						<div id=\"singo\" class=\"singo\" >\r\n");
      out.write("							<span class=\"material-icons singo_img\"> lightbulb </span> <span\r\n");
      out.write("								class=\"board_singo\">신고하기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("   	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/main_ajax.js?ver=1.11\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/main_app.js?ver=5.23\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
