/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-08-31 12:52:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnaView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 조회</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/main_board.css\">\r\n");
      out.write("	\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		  \r\n");
      out.write("<!-- 	<label>글번호</label> -->\r\n");
      out.write("	<div class=\"qna_view_qno\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.qno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("	<div class=\"qna_user_position\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.user_position }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"board_clickPan\">\r\n");
      out.write("		<div onclick=\"imgClickRollback()\" class=\"x_box\">\r\n");
      out.write("			<span class=\"material-icons-outlined \"> close </span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"board_detailContent\">\r\n");
      out.write("			<div class=\"board_detailPan\">\r\n");
      out.write("				<div class=\"board_left_pan\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<label style=\"font-size: 30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr style=\"color: black; width: 100%; margin-bottom: 50px;\">\r\n");
      out.write("					<div id=\"board_main_content\" class=\"board_main_content\">\r\n");
      out.write("						");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"board_comment\">\r\n");
      out.write("						<div id=\"board_comment_tit\" class=\"board_comment_tit\">\r\n");
      out.write("							<p>한줄댓글</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"board_comment_write\">\r\n");
      out.write("							<form action=\"#\" id=\"board_commentId\">\r\n");
      out.write("								<input type=\"text\" id=\"board_commnet\" name=\"board_commnet\"\r\n");
      out.write("									placeholder=\"한 줄 댓글을 남겨주세요.\" autocomplete=\"off\"> <input type=\"hidden\"\r\n");
      out.write("									id=\"user_id\" name=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input\r\n");
      out.write("									type=\"submit\" name=\"board_commnet_submit\" value=\"댓글남기기\">\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"board_comment_show\" class=\"board_comment_show\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"board_right_pan\">\r\n");
      out.write("					<div id=\"board_user_info\" class=\"board_user_info\">\r\n");
      out.write("						<img id=\"board_mainimg\"\r\n");
      out.write("							src=\"");
      out.print(request.getContextPath());
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.user_imgurl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("							alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"board_user_name\" class=\"board_user_name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.user_nickName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"board_content_id\" class=\"board_content_id\"></div>\r\n");
      out.write("					<div id=\"board_title\" class=\"board_title\"></div>\r\n");
      out.write("					<div class=\"board_sub_info\">\r\n");
      out.write("						<div class=\"board_sub_info2\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<span class=\"material-icons-outlined\">visibility</span>\r\n");
      out.write("								<div>조회수</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"board_bestplace\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.viewcnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"board_sub_info2\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<span class=\"material-icons-outlined\">event</span>\r\n");
      out.write("								<div>작성날짜</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"board_besteat\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div style=\"width: 300px; height: 20px;\"><a href=\"./qnaModify?qno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.qno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">게시물 수정</a></div>\r\n");
      out.write("						<div style=\"width: 300px; height: 20px;\"><a href=\"./qnaDelete?qno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnaViewModel.qno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">게시물 삭제</a></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"board_travelPlans\">\r\n");
      out.write("						<div id=\"singo\" class=\"singo\" >\r\n");
      out.write("							<span class=\"material-icons singo_img\"> lightbulb </span> <span\r\n");
      out.write("								class=\"board_singo\">신고하기</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/qna_view.js?ver=1.13\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
